version: 1

devices:
  list:
    - host: 192.168.88.1
  common:
    driver: ssh-command
    timeout: 30s
    command: export
    username: admin
    identity_file: /Users/asphyx/.ssh/id_rsa

storage:
  driver: git
  timeout: 30s
  url: git@github.com:e-asphyx/mikrotik.git
  identity_file: /Users/asphyx/.ssh/id_rsa
  destination_path: '{{.host}}'
  push: true
  name: Eugene Zagidullin
  email: e.asphyx@gmail.com
  commit_message: '{{.time.UTC.Format "2006-01-02T15:04:05Z07:00"}}'

timeout: 30s
interval: 4h
