version: 1

devices:
  list:
    - options:
        host: 192.168.88.1
  common:
    driver: ssh-command
    timeout: 30s
    options:
      command: export
      username: admin
      identity_file: /path/to/routeros_admin_private_key

storage:
  driver: git
  timeout: 30s
  options:
    url: git@github.com:yourorg/networkbackups.git
    identity_file: /path/to/private_git_deploy_key
    destination_path: '{{.host}}'
    push: true
    name: Network Backup
    email: networkbackup@example.net
    commit_message: '{{.time.UTC.Format "2006-01-02T15:04:05Z07:00"}}'

timeout: 30s
interval: 4h
