version: 1

filters:
  - name: mask_timestamp
    filter: regexp
    options:
      expr: '^#\s*\w+/\d+/\d+ \d+:\d+:\d+'
      replace: '# TIMESTAMP_MASKED'

devices:
  list:
    - host: 192.168.88.1
  common:
    driver: ssh-command
    timeout: 30s
    command: export
    username: admin
    identity_file: /Users/asphyx/.ssh/id_rsa
    filters: [mask_timestamp]

storage:
  driver: git
  timeout: 30s
  url: git@github.com:e-asphyx/mikrotik.git
  identity_file: /Users/asphyx/.ssh/id_rsa
  destination_path: '{{.host}}'
  summary: '{{.host}}: {{with .error}}{{.}}{{else}}ok{{end}}'
  push: true
  name: Eugene Zagidullin
  email: e.asphyx@gmail.com
  commit_message: |
    Backup time: {{.time.UTC.Format "2006-01-02T15:04:05Z07:00"}}

    Summary:
    {{range .summary -}}
    {{.}}
    {{end -}}

timeout: 30s
interval: 4h
