version: 1

filters:
  - name: mask_timestamp
    filter: regexp
    options:
      expr: '\w+/\d+/\d+ \d+:\d+:\d+'
      replace: TIMESTAMP_MASKED

devices:
  list:
    - host: 192.168.88.1
  common:
    driver: ssh-command
    timeout: 30s
    command: export
    username: admin
    password: password
    filters: [mask_timestamp]

storage:
  driver: file
  timeout: 30s
  path: 'storage/{{.host}}/{{.time.UTC.Format "2006-01-02T15:04:05Z07:00"}}'

timeout: 30s
interval: 4h
